modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/ash-development/ValkSky2/issues"
license = "Apache-2.0"

[[mods]]
modId = "valkyrienskies"
version = "${version}-fo"
displayName = "Valkyrien Skies 2"
authors = ["Tri0de", "Rubydesic", "ash-development"]
description = '''
Moving blocks with physics :)
Now compatible with Complete Config!
'''
logoFile = "icon.png"

[[dependencies.valkyrienskies]]
modId = "forge"
mandatory = true
versionRange = "[40.2.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.valkyrienskies]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
